apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: backend 
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3AK"
  AMQP_PASS: "cm9ib3Nob3AxMjMK"