apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:   # has to match .spec.template.metadata.labels
      component: mysql
      project: roboshop
      tier: database
  serviceName: "mysql-headless"  # this should be headless service
  replicas: 3
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mysql
        image: gsurendhar/mysql:v1
        envFrom:
        - secretRef:
            name: mysql
        volumeMounts: 
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi
