apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:   # has to match .spec.template.metadata.labels
      component: redis
      project: roboshop
      tier: database
  serviceName: "redis-headless"  # this should be headless service
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels :
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
      - name: redis
        image: "{{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}"
        volumeMounts: 
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi
