apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels: 
    component: cart
    project: roboshop
    tier: backend
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"  