apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
    # deployment labels
  labels:
    component: cart
    project: roboshop
    tier: backend
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: cart
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: cart
        image: "{{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion}}"
        envFrom:
        - configMapRef:
            name: cart
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"