apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels: 
    component: catalogue
    project: roboshop
    tier: backend
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"